services:
  frontend:
    build: .
    container_name: tagline-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: sh -c "npm run dev"
    restart: unless-stopped
    working_dir: /app
