services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tagline-frontend
    ports:
      - "3000:3000"
    volumes:
      # Bind mount the local directory for live reload
      - .:/app
      # Exclude node_modules from the bind mount to prevent permission issues
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_BASE_URL=http://host.docker.internal:8000
      - BACKEND_URL=http://host.docker.internal:8000
      - BACKEND_API_KEY=dev_api_key
      - NEXTAUTH_SECRET=change-this-to-a-secure-random-string
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - STYTCH_PROJECT_ID=${STYTCH_PROJECT_ID}
      - STYTCH_SECRET=${STYTCH_SECRET}
    # Enable debugging
    command: sh -c "npm run dev"
    # For better performance in development
    tmpfs:
      - /tmp
    # Auto-restart if the container crashes
    restart: unless-stopped
    # Set working directory
    working_dir: /app
    # Set default environment variables here if needed
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://localhost:8000
    #   - NEXTAUTH_URL=http://localhost:3000
