services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tagline-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
