# Development docker-compose configuration
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tagline-frontend-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # Bind mount the entire directory but use named volumes for performance
      - .:/app
      - node_modules:/app/node_modules
      - nextjs_cache:/app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

volumes:
  node_modules:
  nextjs_cache:
