"""Add proxy columns

Revision ID: 4815a15eae03
Revises: e05b1143264b
Create Date: 2025-05-04 17:17:43.995707

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4815a15eae03"
down_revision: Union[str, None] = "e05b1143264b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media_objects", sa.Column("proxy", sa.LargeBinary(), nullable=True))
    op.add_column(
        "media_objects", sa.Column("proxy_mimetype", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_objects", "proxy_mimetype")
    op.drop_column("media_objects", "proxy")
    # ### end Alembic commands ###
