"""add thumbnail column

Revision ID: cf52e411bb53
Revises: 9dd6bc8f033c
Create Date: 2025-05-01 22:23:28.695422

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf52e411bb53"
down_revision: Union[str, None] = "9dd6bc8f033c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_objects", sa.Column("thumbnail", sa.LargeBinary(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_objects", "thumbnail")
    # ### end Alembic commands ###
